baseURL = "https://paulcosma.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "home"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Paul Cosma"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "I'm Paul."
  #footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.

  [[params.social]]
      name = "email"
      url = "mailto:gmail@paulcosma.com"

  [[params.social]]
    name = "github"
    url = "https://github.com/paulcosma"

  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/paulcosma"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/paulpcosma/"

  [[params.social]]
    name = "facebook"
    url = "https://facebook.com/paulcosma"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/paulcosma"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/paulpcosma"

  [[params.social]]
    name = "slack"
    url = "https://paulcosma.slack.com"

  [[params.social]]
    name = "telegram"
    url = "https://t.me/paulcosma"

  [[params.personal]]
    name = "mail"
    url = "https://mail.cxpcloud.com"

  [[params.personal]]
    name = "plex"
    url = "https://plex.paulcosma.com"

  [[params.personal]]
    name = "grafana"
    url = "https://grafana.paulcosma.com"

  [[params.personal]]
    name = "monitoring"
    url = "https://monitoring.paulcosma.com"

  [[params.personal]]
    name = "pve"
    url = "https://pve.paulcosma.com"

  [[params.personal]]
    name = "pve2"
    url = "https://pve2.paulcosma.com"

  [[params.personal]]
    name = "irc"
    url = "https://irc.paulcosma.com"

  [[params.personal]]
    name = "haproxy"
    url = "https://haproxy.paulcosma.com"

  [[params.personal]]
    name = "storage"
    url = "https://storage.cxpcloud.com"

  [[params.personal]]
    name = "home"
    url = "https://home.paulcosma.com"

  [[params.personal]]
    name = "kube"
    url = "https://kube.paulcosma.com"

  [[params.personal]]
    name = "rclone"
    url = "https://rclone.paulcosma.com"

  [[params.personal]]
    name = "rancher"
    url = "https://rancher.paulcosma.com"

  [[params.personal]]
    name = "backup"
    url = "https://backup.paulcosma.com"

  [[params.personal]]
    name = "webmail"
    url = "https://webmail.cxpcloud.com"

  [[params.personal]]
    name = "jenkins"
    url = "https://jenkins.paulcosma.com"

  [[params.personal]]
    name = "transmission"
    url = "https://torrent.paulcosma.com"

  [[params.personal]]
    name = "download"
    url = "https://download.paulcosma.com"

  [[params.personal]]
    name = "calculator"
    url = "https://calculator.paulcosma.com"

  [[params.personal]]
    name = "pihole"
    url = "https://pihole.paulcosma.com"

  [[params.personal]]
    name = "jellyfin"
    url = "https://tv.cxpcloud.com"

[menu]

  [[menu.main]]
    name = "about me"
    url = "about/"
    weight = 20
